#if !defined(UM_JULES)
! *****************************COPYRIGHT**************************************
! (C) Crown copyright Met Office. All rights reserved.
! For further details please refer to the file COPYRIGHT.txt
! which you should have received as part of this distribution.
! *****************************COPYRIGHT**************************************

!!****************************************************************************
!! Version control information:
!!
!!   $HeadURL: svn://fcm2/JULES_svn/JULES/trunk/src/io/file_handling/core/file_def_record_dim.inc $
!!   $Author: hadmq $
!!
!!   $LastChangedDate: 2012-08-10 12:50:04 +0100 (Fri, 10 Aug 2012) $
!!   $LastChangedRevision: 486 $
!!
!!****************************************************************************

FUNCTION file_def_record_dim(file, dim_name) RESULT(dim_id)

  USE io_constants, ONLY : MAX_SDF_NAME_LEN

  USE driver_ascii_mod, ONLY : file_ascii_def_record_dim
  USE driver_ncdf_mod, ONLY : file_ncdf_def_record_dim

  IMPLICIT NONE

!-----------------------------------------------------------------------------
! Description:
!   Defines a dimension on the given file, returning the dimension id
!
! Current Code Owner: Matt Pryor
!
! Code Description:
!   Language: Fortran 90.
!   This code is written to JULES coding standards v1.
!-----------------------------------------------------------------------------
! Argument types
  TYPE(file_handle), INTENT(INOUT) :: file
                                  ! The file to define the dimension on
  CHARACTER(len=*), INTENT(IN) :: dim_name
                                  ! The name of the record dimension

! Return type
  INTEGER :: dim_id               ! The dimension id


!-----------------------------------------------------------------------------

  SELECT CASE ( file%driver )
    CASE ( DRIVER_ASCII )
      dim_id = file_ascii_def_record_dim(file%ascii, dim_name)

    CASE ( DRIVER_NCDF )
      dim_id = file_ncdf_def_record_dim(file%ncdf, dim_name)

    CASE DEFAULT
      CALL log_fatal("file_def_record_dim",                                   &
                     "Unrecognised driver - see docs for available drivers")
  END SELECT

  RETURN

END FUNCTION file_def_record_dim
#endif
