#if !defined(UM_JULES)
! *****************************COPYRIGHT**************************************
! (C) Crown copyright Met Office. All rights reserved.
! For further details please refer to the file COPYRIGHT.txt
! which you should have received as part of this distribution.
! *****************************COPYRIGHT**************************************

!!****************************************************************************
!! Version control information:
!!
!!   $HeadURL: svn://fcm2/JULES_svn/JULES/trunk/src/io/file_handling/timeseries/file_ts_def_dim.inc $
!!   $Author: hadmq $
!!
!!   $LastChangedDate: 2012-08-10 12:50:04 +0100 (Fri, 10 Aug 2012) $
!!   $LastChangedRevision: 486 $
!!
!!****************************************************************************

FUNCTION file_ts_def_dim(file, dim_name, dim_len) RESULT(dim_id)

  IMPLICIT NONE

!-----------------------------------------------------------------------------
! Description:
!   Defines a dimension on the given timeseries file, returning the dimension id
!
! Current Code Owner: Matt Pryor
!
! Code Description:
!   Language: Fortran 90.
!   This code is written to JULES coding standards v1.
!-----------------------------------------------------------------------------
! Argument types
  TYPE(file_ts), INTENT(INOUT) :: file
                                  ! The file to define the dimension on
  CHARACTER(len=*), INTENT(IN) :: dim_name
                                  ! The name of the dimension
  INTEGER, INTENT(IN) :: dim_len  ! The length of the dimension

! Return type
  INTEGER :: dim_id               ! The dimension id


!-----------------------------------------------------------------------------

! If we are not in define mode, error out
  IF ( .NOT. file%define_mode )                                               &
    CALL log_fatal("file_ts_def_dim",                                         &
                   "Cannot define dimension - file is not in define mode")

! If adding another dimension will cause us to have too many dimensions,
! error out
  IF ( file%ndims >= MAX_DIM_FILE )                                           &
    CALL log_fatal("file_ts_def_dim",                                         &
                   "Too many dimensions in file - try increasing MAX_DIM_FILE")

!-----------------------------------------------------------------------------
! Store the dimension attributes so that they can be used later to define
! dimensions on actual file(s)
!-----------------------------------------------------------------------------
  file%ndims = file%ndims + 1

! The returned dimension id is just the index in the dims array on the file object
  dim_id = file%ndims

  file%dims(dim_id)%name   = dim_name
  file%dims(dim_id)%length = dim_len

  RETURN

END FUNCTION file_ts_def_dim
#endif
